## Creating a logistic regression to predict absenteeism

**Import the relevant libraries**

In [3]:
import pandas as pd
import numpy as np

**Load the data**

In [5]:
data_preprocessed=pd.read_csv('C:/Users/bhanu/Downloads/Absenteeism_preprocessed.csv')

In [6]:
data_preprocessed.head(10)

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of Week  \
0         0         0         0         1            7            1   
1         0         0         0         0            7            1   
2         0         0         0         1            7            2   
3         1         0         0         0            7            3   
4         0         0         0         1            7            3   
5         0         0         0         1            7            4   
6         0         0         0         1            7            4   
7         0         0         0         1            7            4   
8         0         0         1         0            7            0   
9         0         0         0         1            7            0   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   
5                     179                51   38                  239.554   
6                     361                52   28                  239.554   
7                     260                50   36                  239.554   
8                     155                12   34                  239.554   
9                     235                11   37                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2  
5               31          0         0     0                          2  
6               27          0         1     4                          8  
7               23          0         4     0                          4  
8               25          0         2     0                         40  
9               29          1         1     1                          8

**Create the targets**

In [8]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [9]:
targets=np.where(data_preprocessed['Absenteeism Time in Hours']>
                 data_preprocessed['Absenteeism Time in Hours'].median(),1,0)

In [10]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [11]:
data_preprocessed['Excessive Absenteeism']=targets

In [12]:
data_preprocessed.head(5)

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of Week  \
0         0         0         0         1            7            1   
1         0         0         0         0            7            1   
2         0         0         0         1            7            2   
3         1         0         0         0            7            3   
4         0         0         0         1            7            3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

**A comment on the targets**

In [14]:
targets.sum()/targets.shape[0]

0.45571428571428574

In [15]:
data_with_targets=data_preprocessed.drop(['Absenteeism Time in Hours','Day of Week','Daily Work Load Average','Distance to Work'],axis=1)

In [16]:
data_with_targets

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                       289   33               30          0         2     1   
1                       118   50               31          0         1     0   
2                       179   38               31          0         0     0   
3                       279   39               24          0         2     0   
4                       289   33               30          0         2     1   
..                      ...  ...              ...        ...       ...   ...   
695                     179   40               22          1         2     0   
696                     225   28               24          0         1     2   
697                     330   28               25          1         0     0   
698                     235   32               25          1         0     0   
699                     291   40               25          0         1     1   

     Excessive Absenteeism  
0                        1  
1                        0  
2                        0  
3                        1  
4                        0  
..                     ...  
695                      1  
696                      0  
697                      1  
698                      0  
699                      0  

[700 rows x 12 columns]

In [17]:
data_with_targets is data_preprocessed

False

In [18]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0         0         0         0         1            7   
1         0         0         0         0            7   
2         0         0         0         1            7   
3         1         0         0         0            7   
4         0         0         0         1            7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                     289   33               30          0         2     1   
1                     118   50               31          0         1     0   
2                     179   38               31          0         0     0   
3                     279   39               24          0         2     0   
4                     289   33               30          0         2     1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

**Select the inputs for regression**

In [20]:
data_with_targets.shape

(700, 12)

In [21]:
data_with_targets.iloc[:,0:14]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                       289   33               30          0         2     1   
1                       118   50               31          0         1     0   
2                       179   38               31          0         0     0   
3                       279   39               24          0         2     0   
4                       289   33               30          0         2     1   
..                      ...  ...              ...        ...       ...   ...   
695                     179   40               22          1         2     0   
696                     225   28               24          0         1     2   
697                     330   28               25          1         0     0   
698                     235   32               25          1         0     0   
699                     291   40               25          0         1     1   

     Excessive Absenteeism  
0                        1  
1                        0  
2                        0  
3                        1  
4                        0  
..                     ...  
695                      1  
696                      0  
697                      1  
698                      0  
699                      0  

[700 rows x 12 columns]

In [22]:
data_with_targets.iloc[:,:-1]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
0                       289   33               30          0         2     1  
1                       118   50               31          0         1     0  
2                       179   38               31          0         0     0  
3                       279   39               24          0         2     0  
4                       289   33               30          0         2     1  
..                      ...  ...              ...        ...       ...   ...  
695                     179   40               22          1         2     0  
696                     225   28               24          0         1     2  
697                     330   28               25          1         0     0  
698                     235   32               25          1         0     0  
699                     291   40               25          0         1     1  

[700 rows x 11 columns]

In [23]:
unscaled_inputs=data_with_targets.iloc[:,:-1]

**Standardize the data**

In [25]:
##from sklearn.preprocessing import StandardScaler

##absenteeism_scaler=StandardScaler()

In [26]:
from sklearn.base import BaseEstimator,TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator,TransformerMixin):

   

    def __init__(self,columns):

        self.scaler=StandardScaler()

        self.columns=columns

        self.mean_=None

        self.var_=None

       

    def fit(self,X,y=None):

        self.scaler.fit(X[self.columns],y)

        self.mean_=np.mean(X[self.columns])

        self.var_=np.var(X[self.columns])

        return self

   

    def transform(self,X,y=None):

        init_col_order=X.columns

        X_scaled=pd.DataFrame(self.scaler.transform(X[self.columns]),columns=self.columns)

        X_not_scaled=X.loc[:,~X.columns.isin(self.columns)]

        return pd.concat([X_not_scaled,X_scaled],axis=1)[init_col_order]

In [27]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [28]:
##columns_to_scale=['Month Value','Day of Week', 'Transportation Expense', 'Distance to Work', 'Age',
       ##'Daily Work Load Average', 'Body Mass Index','Children', 'Pets']

columns_to_omit=['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']

In [29]:
columns_to_scale=[x for x in unscaled_inputs.columns.values if x not in columns_to_omit]            

In [30]:
absenteeism_scaler=CustomScaler(columns_to_scale)

In [31]:
absenteeism_scaler.fit(unscaled_inputs)

C:\Users\bhanu\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:3785: FutureWarning: The behavior of DataFrame.var with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return var(axis=axis, dtype=dtype, out=out, ddof=ddof, **kwargs)


CustomScaler(columns=['Month Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'])

In [32]:
scaled_inputs=absenteeism_scaler.transform(unscaled_inputs)

In [33]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1     0.182726   
1           0         0         0         0     0.182726   
2           0         0         0         1     0.182726   
3           1         0         0         0     0.182726   
4           0         0         0         1     0.182726   
..        ...       ...       ...       ...          ...   
695         1         0         0         0    -0.388293   
696         1         0         0         0    -0.388293   
697         1         0         0         0    -0.388293   
698         0         0         0         1    -0.388293   
699         0         0         0         1    -0.388293   

     Transportation Expense       Age  Body Mass Index  Education  Children  \
0                  1.005844 -0.536062         0.767431          0  0.880469   
1                 -1.574681  2.130803         1.002633          0 -0.019280   
2                 -0.654143  0.248310         1.002633          0 -0.919030   
3                  0.854936  0.405184        -0.643782          0  0.880469   
4                  1.005844 -0.536062         0.767431          0  0.880469   
..                      ...       ...              ...        ...       ...   
695               -0.654143  0.562059        -1.114186          1  0.880469   
696                0.040034 -1.320435        -0.643782          0 -0.019280   
697                1.624567 -1.320435        -0.408580          1 -0.919030   
698                0.190942 -0.692937        -0.408580          1 -0.919030   
699                1.036026  0.562059        -0.408580          0 -0.019280   

         Pets  
0    0.268487  
1   -0.589690  
2   -0.589690  
3   -0.589690  
4    0.268487  
..        ...  
695 -0.589690  
696  1.126663  
697 -0.589690  
698 -0.589690  
699  0.268487  

[700 rows x 11 columns]

In [34]:
scaled_inputs.shape

(700, 11)

**Spilt the data into train & test and shuffle**

**import the relevant module**

In [37]:
from sklearn.model_selection import train_test_split

**Split**

In [39]:
train_test_split(scaled_inputs,targets)

[     Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
 553         0         0         0         1     1.324766   
 330         1         0         0         0     1.324766   
 128         0         0         0         1    -1.530333   
 85          1         0         0         0     1.324766   
 50          0         0         0         0     0.753746   
 ..        ...       ...       ...       ...          ...   
 594         0         0         1         0    -1.244823   
 247         0         0         0         1     0.182726   
 398         0         0         0         1    -0.959313   
 422         0         0         0         1    -0.673803   
 385         0         0         0         1    -1.244823   
 
      Transportation Expense       Age  Body Mass Index  Education  Children  \
 553                2.213108 -0.849811        -0.408580          0  1.780219   
 330                0.356940  0.718933        -0.878984          0 -0.919030   
 128               -1.5746

In [40]:
x_train,x_test,y_train,y_test=train_test_split(scaled_inputs,targets,train_size=0.8,random_state=80)

In [41]:
print(x_train.shape,y_train.shape)

(560, 11) (560,)


In [42]:
print(x_test.shape,y_test.shape)

(140, 11) (140,)


**Logistic regression with sklearn**

In [44]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

**Training the model**

In [46]:
reg=LogisticRegression()

In [47]:
reg.fit(x_train,y_train)

LogisticRegression()

In [48]:
reg.score(x_train,y_train)

0.7839285714285714

**Manually check the accuracy**

In [50]:
model_outputs=reg.predict(x_train)

In [51]:
model_outputs

array([0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,

In [52]:
y_train

array([1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,

In [141]:
model_outputs==y_train

array([False,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True, False,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True, False, False,  True,  True, False,  True,  True,  True,
        True,  True, False,  True, False,  True, False, False,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True, False,
       False,  True, False,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True, False,
        True,  True,

In [54]:
np.sum(model_outputs==y_train)

439

In [55]:
model_outputs.shape[0]

560

In [56]:
np.sum(model_outputs==y_train)/model_outputs.shape[0]

0.7839285714285714

**Finding the intercept and coefficient**

In [58]:
reg.intercept_

array([-1.99617955])

In [59]:
reg.coef_

array([[ 3.1370163 , -0.16380658,  3.34165696,  1.14615326,  0.09799991,
         0.59038234, -0.17813324,  0.39094116,  0.11129131,  0.44158835,
        -0.2189802 ]])

In [60]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [61]:
feature_name=unscaled_inputs.columns.values

In [62]:
summary_table=pd.DataFrame(columns=['Feature name'],data=feature_name)
summary_table['Coefficient']=np.transpose(reg.coef_)
summary_table

Feature name  Coefficient
0                 Reason_1     3.137016
1                 Reason_2    -0.163807
2                 Reason_3     3.341657
3                 Reason_4     1.146153
4              Month Value     0.098000
5   Transportation Expense     0.590382
6                      Age    -0.178133
7          Body Mass Index     0.390941
8                Education     0.111291
9                 Children     0.441588
10                    Pets    -0.218980

In [63]:
summary_table.index=summary_table.index+1
summary_table.loc[0]=['Intercept',reg.intercept_[0]]
summary_table=summary_table.sort_index()
summary_table

Feature name  Coefficient
0                Intercept    -1.996180
1                 Reason_1     3.137016
2                 Reason_2    -0.163807
3                 Reason_3     3.341657
4                 Reason_4     1.146153
5              Month Value     0.098000
6   Transportation Expense     0.590382
7                      Age    -0.178133
8          Body Mass Index     0.390941
9                Education     0.111291
10                Children     0.441588
11                    Pets    -0.218980

**Interpreting the coefficient**

In [65]:
summary_table['Odds_ratio']=np.exp(summary_table.Coefficient)

In [66]:
summary_table

Feature name  Coefficient  Odds_ratio
0                Intercept    -1.996180    0.135853
1                 Reason_1     3.137016   23.035035
2                 Reason_2    -0.163807    0.848906
3                 Reason_3     3.341657   28.265923
4                 Reason_4     1.146153    3.146067
5              Month Value     0.098000    1.102963
6   Transportation Expense     0.590382    1.804678
7                      Age    -0.178133    0.836831
8          Body Mass Index     0.390941    1.478372
9                Education     0.111291    1.117720
10                Children     0.441588    1.555175
11                    Pets    -0.218980    0.803338

In [67]:
summary_table.sort_values('Odds_ratio',ascending=False)

Feature name  Coefficient  Odds_ratio
3                 Reason_3     3.341657   28.265923
1                 Reason_1     3.137016   23.035035
4                 Reason_4     1.146153    3.146067
6   Transportation Expense     0.590382    1.804678
10                Children     0.441588    1.555175
8          Body Mass Index     0.390941    1.478372
9                Education     0.111291    1.117720
5              Month Value     0.098000    1.102963
2                 Reason_2    -0.163807    0.848906
7                      Age    -0.178133    0.836831
11                    Pets    -0.218980    0.803338
0                Intercept    -1.996180    0.135853

**Testing the model**

In [69]:
reg.score(x_test,y_test)

0.7428571428571429

In [70]:
predicted_proba=reg.predict_proba(x_test)
predicted_proba

array([[0.29492867, 0.70507133],
       [0.7788879 , 0.2211121 ],
       [0.08149996, 0.91850004],
       [0.76409402, 0.23590598],
       [0.14933076, 0.85066924],
       [0.42405711, 0.57594289],
       [0.45905946, 0.54094054],
       [0.86792355, 0.13207645],
       [0.7788879 , 0.2211121 ],
       [0.73579427, 0.26420573],
       [0.23457892, 0.76542108],
       [0.49336289, 0.50663711],
       [0.58157409, 0.41842591],
       [0.89153652, 0.10846348],
       [0.82416475, 0.17583525],
       [0.41657901, 0.58342099],
       [0.38197449, 0.61802551],
       [0.44520591, 0.55479409],
       [0.86528209, 0.13471791],
       [0.30786626, 0.69213374],
       [0.20761542, 0.79238458],
       [0.45905946, 0.54094054],
       [0.9517335 , 0.0482665 ],
       [0.17434284, 0.82565716],
       [0.52319561, 0.47680439],
       [0.52319561, 0.47680439],
       [0.40725699, 0.59274301],
       [0.72120103, 0.27879897],
       [0.32482931, 0.67517069],
       [0.1698415 , 0.8301585 ],
       [0.

In [71]:
predicted_proba.shape

(140, 2)

In [72]:
predicted_proba[:,1]

array([0.70507133, 0.2211121 , 0.91850004, 0.23590598, 0.85066924,
       0.57594289, 0.54094054, 0.13207645, 0.2211121 , 0.26420573,
       0.76542108, 0.50663711, 0.41842591, 0.10846348, 0.17583525,
       0.58342099, 0.61802551, 0.55479409, 0.13471791, 0.69213374,
       0.79238458, 0.54094054, 0.0482665 , 0.82565716, 0.47680439,
       0.47680439, 0.59274301, 0.27879897, 0.67517069, 0.8301585 ,
       0.46472627, 0.23608465, 0.44448749, 0.57594289, 0.67517069,
       0.62602849, 0.81234252, 0.22303578, 0.66900445, 0.17053216,
       0.06736675, 0.91557246, 0.51486331, 0.72999959, 0.96498267,
       0.19827632, 0.23303155, 0.58276157, 0.1221965 , 0.61205579,
       0.21633097, 0.13862788, 0.227922  , 0.13801296, 0.15991198,
       0.81234252, 0.96941451, 0.86586536, 0.86586536, 0.30379605,
       0.62602849, 0.13532044, 0.53579133, 0.78540113, 0.58276157,
       0.4081293 , 0.18786889, 0.58342099, 0.21633097, 0.16787223,
       0.27347607, 0.63114588, 0.6836898 , 0.76018709, 0.53579

**Save the model**

In [74]:
import pickle

In [75]:
with open('model','wb') as file:
    pickle.dump(reg,file)

In [76]:
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler,file)